<?php
// IBLOCKS
const SIMPLE_ADS_IBLOCK_ID = 1;
const PROPERTY_ADS_IBLOCK_ID = 2;
const AUTO_IBLOCK_ID = 3;
const MOTO_IBLOCK_ID = 7;
const SCOOTER_IBLOCK_ID = 8;
const PROPERTY_TYPES_HL_ID = 17;
const LIVING_PROP_SECTIONS_ID = [34, 35];
const COMMERCICAL_PROP_SECTIONS_ID = [32, 33];
const NEW_BUILDINGS_PROP_SECTIONS_ID = [31, 30];
const MAP_REGIONS_HL_ID = 34;
const REAL_ESTATE_LIVE_RENT_SECTION_ID = 34;
const FILTER_EXTRA_SHOW_COUNT = 3; //отвечает за то сколько свойств будет показано перед фильтром (минимум 2)
const ADD_AUTO_BODY_TYPES_SHOW_COUNT = 4; //отвечает за то сколько кузовов(пикап, минивен..) будет выводиться на странице добавления АВТО перед кнопкой show all (надо указывать на 1 меньше так как счёт идёт с 0 а не с 1)
/* Системные константы */
const RESIDENTIAL_BUY_SECTION_ID = 35;
const RESIDENTIAL_RENT_SECTION_ID = 34;
const RESIDENTIAL_SECTION_ID = 27;
const RESIDENTAL_SECTION_ARRAY = [RESIDENTIAL_BUY_SECTION_ID, RESIDENTIAL_RENT_SECTION_ID ,RESIDENTIAL_SECTION_ID];


const COMMERCIAL_BUY_SECTION_ID = 33;
const COMMERCIAL_RENT_SECTION_ID = 32;
const COMMERCIAL_SECTION_ID = 28;
const COMMERCIAL_SECTION_ARRAY = [COMMERCIAL_BUY_SECTION_ID, COMMERCIAL_RENT_SECTION_ID ,COMMERCIAL_SECTION_ID];


const NEW_BUY_SECTION_ID = 31;
const NEW_RENT_SECTION_ID = 30;
const NEW_SECTION_ID = 29;
const NEWL_SECTION_ARRAY = [NEW_BUY_SECTION_ID, NEW_RENT_SECTION_ID ,NEW_SECTION_ID];
const IBLOCK_PROPERTY_MAP_LAYOUT_JSON_PROP_ID = 201;
const IBLOCK_PROPERTY_MAP_LAYOUT_BIG_PROP_ID = 200;
const IBLOCK_PROPERTY_PROP_COUNT_ROOMS_PROP_ID = 109;
const IBLOCK_PROPERTY_PROP_TYPE_APART_PROP_ID = 165;

const IMMUTABLE_PROPERTY_FILTER_PROPS = [
    'MAP_LAYOUT_JSON',
    'MAP_LAYOUT_BIG',
    'PRICE',
    'PROP_AREA_2',
    'PROP_COUNT_ROOMS',
    'PROP_FREE_LAYOUT',
    'PROP_STUDIO',
    'PROP_TYPE_APART',
    'PROP_FLOOR',
    'NOT_FIRST',
    'NOT_LAST',
    'PROP_Completion',
    'IMMEDIATELY_ENTRY',
];